### PR TITLE
Delete T.T

### PR DESCRIPTION
**Pull request by SleepyF0X**
F*** you Kolya

### CODE REVIEW

**Comment by SleepyF0X** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by WerewolfNet** [comment]
Ору

**Comment by SleepyF0X** [comment]
Opy? What is Opy?

**Review by WerewolfNet — APPROVED** [review]
Понеслась

**Pull request merged**
